# Header
language: r
cache: 
  packages: true
  directories:
  - $HOME/usr/local
  
before_install:
   - echo 'options(Ncpus = 2)' >> ~/.Rprofile
   - export PATH=$PATH:$HOME/usr/local/bin
   - sh ./cmtk_build.sh
   
warnings_are_errors: true

jobs:
  include:
  - stage:
       name: nat installation
       script:
        - Rscript -e 'remotes::install_github("natverse/nat")'
    - stage: precache
      script: true
    - stage: test
      script:
        - R CMD build .
        - R CMD check --as-cran
        - Rscript -e 'res=devtools::test(reporter="summary");df=as.data.frame(res);if(sum(df$failed) > 0 || any(df$error)) {q(status=1)}'
      after_script:
        - if [ -e ${TRAVIS_BUILD_DIR}/OOSAP.Rcheck/00install.out ];then cat ${TRAVIS_BUILD_DIR}/OOSAP.Rcheck/00install.out; else echo '00install.log not found'; fi

addons:
  apt:
    packages:
    - libglu1-mesa-dev
    
#env
env:
  global:
    - secure: U5L4JHPa5/mpcDjL60XZVDXtT/nQe4lyhCG6pIj7dF8N6iLRO/vh0ChPxZsBhunKaNMnu59MEqn9nvp09kodV7DzW1nNV+UVi2ZtXpAFejHOK6T4d31vGShCnoM5BkTeMp7exX8yfKWw3Zw0JY47sHTLFihYbwUFqsus0aqT0hIK
    - RGL_USE_NULL=TRUE
