# Header
language: r
cache:
  packages: true
  directories:
  - $HOME/usr/local

warnings_are_errors: true

matrix:
  include:
    before_install:
         - echo 'options(Ncpus = 2)' >> ~/.Rprofile
         - export PATH=$PATH:$HOME/usr/local/bin
         - sh ./cmtk_build.sh
         - R -e 'install.packages("remotes")'
    install:
         - R -e 'remotes::install_cran(c("rgl", "nabor", "filehash","digest", "plyr", "yaml", "progress"),dependencies = TRUE)'
         - R -e 'remotes::install_cran(c("graph","igraph"),dependencies = TRUE)'
         - R -e 'remotes::install_github("natverse/nat.utils",dependencies = TRUE)'
         - R -e 'remotes::install_github("natverse/nat",dependencies = FALSE)'
         - R -e 'remotes::install_deps(dependencies = TRUE)'
    script: true

addons:
  apt:
    packages:
    - libglu1-mesa-dev
    - libmagick++-dev

#env
env:
  global:
    - secure: U5L4JHPa5/mpcDjL60XZVDXtT/nQe4lyhCG6pIj7dF8N6iLRO/vh0ChPxZsBhunKaNMnu59MEqn9nvp09kodV7DzW1nNV+UVi2ZtXpAFejHOK6T4d31vGShCnoM5BkTeMp7exX8yfKWw3Zw0JY47sHTLFihYbwUFqsus0aqT0hIK
    - RGL_USE_NULL=TRUE
