# Header
language: r
cache: packages

jobs:
  include:
    - stage: prepare cache
    - stage: test
        script:
        - curl -OL https://raw.githubusercontent.com/jefferis/nat/master/build-cmtk.sh
        - bash build-cmtk.sh
        - export PATH=$PATH:$HOME/usr/local/bin
        script: true
warnings_are_errors: true
before_install:
  - echo 'options(Ncpus = 2)' >> ~/.Rprofile
addons:
  apt:
    packages:
    - libglu1-mesa-dev
    
#env
env:
  global:
    - secure: U5L4JHPa5/mpcDjL60XZVDXtT/nQe4lyhCG6pIj7dF8N6iLRO/vh0ChPxZsBhunKaNMnu59MEqn9nvp09kodV7DzW1nNV+UVi2ZtXpAFejHOK6T4d31vGShCnoM5BkTeMp7exX8yfKWw3Zw0JY47sHTLFihYbwUFqsus0aqT0hIK
    - RGL_USE_NULL=TRUE
